"""empty message

Revision ID: 684997acab42
Revises: 
Create Date: 2025-03-30 17:08:34.470660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '684997acab42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analysis_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_path', sa.VARCHAR(length=255), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('message', sa.VARCHAR(length=255), nullable=True),
    sa.Column('class_label', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('request_timestamp', sa.DateTime(timezone=6), nullable=True),
    sa.Column('response_timestamp', sa.DateTime(timezone=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_analysis_log')
    # ### end Alembic commands ###
